USE ADVENTUREWORKS2014;
GO

IF
    NOT EXISTS (
        SELECT 1
        FROM SYS.SCHEMAS
        WHERE NAME = 'mart'
    )
    BEGIN
        EXEC ('CREATE SCHEMA mart');
    END;
GO

CREATE OR ALTER VIEW MART.VW_MONTHLY_SALES
AS
SELECT
    CAST(SUM(SUBTOTAL) AS DECIMAL(19, 4)) AS SUBTOTAL_AMOUNT,
    CAST(SUM(TAXAMT) AS DECIMAL(19, 4)) AS TAX_AMOUNT,
    CAST(SUM(FREIGHT) AS DECIMAL(19, 4)) AS FREIGHT_AMOUNT,
    CAST(SUM(TOTALDUE) AS DECIMAL(19, 4)) AS TOTAL_SALES_AMOUNT,
    DATEFROMPARTS(YEAR(ORDERDATE), MONTH(ORDERDATE), 1) AS SALES_MONTH,
    COUNT(*) AS ORDER_COUNT
FROM SALES.SALESORDERHEADER
GROUP BY
    DATEFROMPARTS(YEAR(ORDERDATE), MONTH(ORDERDATE), 1);
GO
